### ISSUE TITLE
MeshAgent Installation Error Cannot Read Property

### ISSUE THREAD

**Issue by bloesss** [Ylianst/MeshAgent#186] opened 2023-06-05 08:29 UTC
Hi,

we are using Meshagent on several Computers.
But the same Installer Skript that always went fine, fails on one Win10/64 Computer:

[2023-06-05 10:24:17 AM] [AD262CB981431433] ..\microscript\ILibDuktape_ScriptContainer.c:1667 (0,0) uncaught: 'cannot read property \x27split\x27 of null'
C:\Users\Admin\Downloads>

**Comment by si458** [comment] 2024-07-13 12:06
duplicate of https://github.com/Ylianst/MeshAgent/issues/121

**Closed by si458** 2024-07-13 12:06 UTC
