### ISSUE TITLE
MeshAgent self update doesnt work

### ISSUE THREAD

**Issue by marco-vogt** [Ylianst/MeshAgent#23] opened 2019-10-22 09:57 UTC
After updating my MeshCentral server, all my agents attempted to update themselves.
On some systems (mostly windows 7), it works correctly. On many other systems (mostly windows 10 64bit) it didnt work.
When i try to "meshagent connect" with "controlChannelDebug=1" i get following logs:

```
[2019-10-22 11:54:49 AM] Attempting to connect to Server...
[2019-10-22 11:54:49 AM] Connecting to: 671EC973D757E5B1D1E93B8D09EF259CB8199404AE5928527C7D7F6C55C1F788EBEED29A7756B8AD0F7DE045786CCB35
[2019-10-22 11:54:49 AM] Control Channel Connection Established...
[2019-10-22 11:54:49 AM] Sending Authentication Data...
[2019-10-22 11:54:49 AM] ProcessCommand(1)...
[2019-10-22 11:54:49 AM] Processing Authentication Request...
[2019-10-22 11:54:49 AM] ProcessCommand(2)...
[2019-10-22 11:54:49 AM] Processing Authentication Verification...
[2019-10-22 11:54:49 AM] ProcessCommand(4)...
[2019-10-22 11:54:49 AM] Authentication Complete...
[2019-10-22 11:54:49 AM] ProcessCommand(12)...
[2019-10-22 11:54:49 AM] BinaryCommand(12, 0)...
[2019-10-22 11:54:49 AM] ProcessCommand(10)...
[2019-10-22 11:54:49 AM] BinaryCommand(10, 0)...
[2019-10-22 11:54:49 AM] ProcessCommand(13)...
[2019-10-22 11:54:49 AM] BinaryCommand(13, 0)...
[2019-10-22 11:54:49 AM] ProcessCommand(14)...
[2019-10-22 11:54:49 AM] BinaryCommand(14, 1)...
[2019-10-22 11:54:50 AM] ProcessCommand(10)...
[2019-10-22 11:54:50 AM] BinaryCommand(10, 0)...
[2019-10-22 11:54:50 AM] ProcessCommand(31522)...
```

Also, a Meshagent.update.exe gets created, but it only ever gets exactly 64kb large and then nothing happens.

**Comment by Ylianst** [comment] 2019-10-27 21:20
This is not good. As a result of [this problem](https://github.com/Ylianst/MeshCentral/issues/599), the new MeshCentral servers will serve MeshAgent updates with some change in them. I would love to see if that is causing the problem. If you update to the just published MeshCentral v0.4.3-h. You can add "AgentsInRAM":false in settings section of the config.json:

{
  "settings": {
    "Port": 443,
    "RedirPort": 80,
    "AgentsInRAM": false
  }
}

If you don't set this, it will default to only loading the 32 and 64bit Windows agents in RAM and modifying them. If set to true, all agents binaries are loaded in server RAM and the 2 Windows agents being modified. If set to false, no agent is loaded in RAM and none of them are modified.

If you update to MeshCentral v0.4.3-h and set "AgentsInRAM":false and the update starts working, there is a problem with the MeshCentral server modifying the agent. Let me know what you see.

**Comment by marco-vogt** [comment] 2019-10-28 10:18
> 
> 
> This is not good. Here is a possible solution. As a result of [this problem](https://github.com/Ylianst/MeshCentral/issues/599), the new MeshCentral servers will serve Windows MeshAgent updates with some change in them. I would know if that is causing the problem. If you update to the just published MeshCentral v0.4.3-h. You can add "AgentsInRAM":false in settings section of the config.json:
> 
> ```
> {
>   "settings": {
>     "Port": 443,
>     "RedirPort": 80,
>     "AgentsInRAM": false
>   }
> }
> ```
> 
> If you don't set this, it will default to only loading the 32 and 64bit Windows agents in RAM and modifying them. If set to true, all agents binaries are loaded in server RAM and the two Windows agents will be modified. If set to false, no agent is loaded in RAM and none of them are modified.
> 
> If you update to MeshCentral v0.4.3-h and set "AgentsInRAM":false and the update starts working, there is a problem with the MeshCentral server modifying the agent. Let me know what you see.

Hey @Ylianst ,

thanks for your reply but unfortunately this didnt fix it.
Still getting to 64kb of filesize and stopping.

Im noticing that on my Windows 7 machines, the self updates work fine. On Windows 10 machines, its hit or miss and on windows server machines , they dont work.

Is there anything more i can get you from my side in order to track this down?

**Comment by krayon007** [comment] 2019-10-28 12:43
If you set "logUpdate=1" in the msh file and restart the agent, it will log each step of the update process including when it tries to download the update itself.

**Comment by krayon007** [comment] 2019-10-28 13:00
By the way, it's interesting you only show one binary command 14 packet. That command ID is the agent update block, where a 64k chunk is received from the server. You should have LOTS of those.

**Comment by Ylianst** [comment] 2019-10-28 17:43
Just published MeshCentral v0.4.3-i with better tracing for the agent update process and one fix so the server does not try to update the meshcore.js when updating the agent.

You can now type:

`node node_modules/meshcentral --debug agent,agentupdate`

To see the server side of the update process. Or, if you don't want to restart the server to debug, go in the "My Server" -> "Trace" tab and select the two tracing options (see pictures below). Once you have a trace, you can save it using the little blue arrow on the upper right on the screen.

Later today, I will create a new server option to reduce the size of each block sent to the agent, just in case 64k is too big.

![x1](https://user-images.githubusercontent.com/1319013/67702727-8041e900-f96f-11e9-8ce5-b144be9e323f.png)
![x2](https://user-images.githubusercontent.com/1319013/67702732-833cd980-f96f-11e9-9281-ce04ab41f203.png)

**Comment by marco-vogt** [comment] 2019-10-28 18:05
Thanks!

With logUpdate=1, i get:

```
[2019-10-28 06:52:22 PM] Attempting to connect to Server...
[2019-10-28 06:52:22 PM] Attempting to connect to Server...
[2019-10-28 06:52:22 PM] Connecting to: 671EC973D757E5B1D1E93B8D09EF259CB8199404AE5928527C7D7F6C55C1F788EBEED29A7756B8AD0F7DE045786CCB35

[2019-10-28 06:52:22 PM] Connection Established [0000000000578D30]...
[2019-10-28 06:52:22 PM] SelfUpdate -> Starting download...
```

Then nothing happens.

After updaing to v0.4.3-i, there is an improvement though. The update downloads fine, a new MeshAgent.update.exe gets created and it download successfully. The problem is though, after the download is complete, the old MeshAgent.exe doesn't "get updated". The new MeshAgent.update.exe just sits in the same folder and nothing happens.

What I now would need to is, delete the MeshAgent.exe, rename the MeshAgent.update.exe to MeshAgent.exe and start it again.

So, while the initial problem was fixed as it seems, there is now a new problem that the existing MeshAgent.exe doesnt get updated by itself.

Fyi: Im using the MeshAgent from the commandline with MeshAgent /connect. I dont use it as a service

**Comment by Ylianst** [comment] 2019-10-29 00:00
Published MeshCentral v0.4.3-j with a new "AgentUpdateBlockSize" option in the settings. Can you try this?

{
  "settings": {
    "Port": 443,
    "RedirPort": 80,
    "AgentsInRAM": false,
    "AgentUpdateBlockSize": 2048,
  }
}

The default AgentUpdateBlockSize is 65531 and the acceptable values are between 1024 and 65531. I should try this because we have had issues with the agent dealing with big blocks of data before and I have done 10's of updates on my test machines and can't get this to fail.

It think this is an agent problem, but I am the server guy... so a bit bias. I did change one thing of significance in the server, the meshcore.js can't be updated when the agent is performing an update. So the agent should be getting one less command. This said, most of the change is tracing which I wanted to do anyway.

If you can try a smaller block size for the update and let us know if that works, would be wonderful. Thanks in advance.

**Comment by marco-vogt** [comment] 2019-11-05 14:33
Hey @Ylianst ,

sorry i was on holiday and couldn't really test this.

After adding this to the settings, it -kinda- works now.

The Agent is doing its update and it ends up being like this:
![1](https://user-images.githubusercontent.com/32278960/68216583-5fb60680-ffe1-11e9-90a1-d3097d2faff8.PNG)
Then, the agent closes itself and nothing happens. If i restart the agent, it deletes the .update.exe file and everything is fine.

Is there anything we can do so i dont have to manually restart the agent after the update is done?

Note i am using the agent from the command line with "meshagent connect" -  maybe that helps.

The log looks like this:
```
[2019-11-05 03:30:08 PM] Connection Established [000002B825FC9D00]...
[2019-11-05 03:30:09 PM] SelfUpdate -> Starting download...
[2019-11-05 03:31:13 PM] SelfUpdate -> Download Complete... Hash verified
[2019-11-05 03:31:13 PM] SelfUpdate -> Diagnostic Agent unavailable to assist with self update
[2019-11-05 03:31:13 PM] SelfUpdate -> Stopping Chain (1)
[2019-11-05 03:31:13 PM] SelfUpdate -> Updating...
```
After this, the agent closes itself.

**Comment by githubbiswb** [comment] 2020-08-09 19:26
I can confirm this is still and issue, and I have lab environment Windows 10VMs where if you want to see this I would be happy to provide you some login information to see it for yourself. 

I also found a log in the meshagent folder I have called MeshAgent-DeviceGroup.update.jlog which reapeats the same message over and over again which is
"Service Manager Error: could not open ServiceManager"

This error is logical because I am not running this as an admin, but as a user. This is because I need the agent to start with command prompt (as mentioned by the other poster), because where I am running this is in a Windows 10 VM where people connect into it with RDP to work. But if you install the agent as an admin, you won't be able to interact with the RDP session. Instead you just get the login screen. This makes seeing the screen impossible for remote support siutations. 

To work around this I made a batch file that fires the agent off on login of the user, but of course this is with user permissions. This works great for the screen sharing I need to do, but if the update is trying to access the services to get itself setup in there, that won't work in this scenario. 

Again if you want to see it, I would be happy to share login info or share a screen with you as well. Whatever works best. 

Thank you for the fantastic work, I am pretty new to MeshCentral, and am very much impressed with the quality here, well done. If we meet in person, beers on me.

**Comment by krayon007** [comment] 2020-08-09 19:37
You should be able to install the agent as local system. When you connect remote desktop, there should be a menu showing all the available sessions, allowing you to connect to an existing RDP session. Running the agent as a local user should not be necessary.

**Comment by githubbiswb** [comment] 2020-08-09 19:39
> 
> 
> You should be able to install the agent as local system. When you connect remote desktop, there should be a menu showing all the available sessions, allowing you to connect to an existing RDP session. Running the agent as a local user should not be necessary.

I will look into that for sure, I am not sold on the idea of running the agent as the user, it just worked for what we needed to accomplish, and I am all for making it better. 

Still, my guess is the earlier issue is likely in the same camp, the real issue is the agent is being run as a user and it can't make a service so it hangs. With that said, this might go in the category of won't fix if doing so is really unecessary based on krayon007's point.

**Comment by githubbiswb** [comment] 2020-08-10 23:05
Yep, the local account install worked perfectly for me and now I get presented with the menu that allows me to choose either the RDP session or the console session and the agent updated as expected since it has rights to do what it needs to do. For those curious how to install something as Local System as indicated by krayon007. I used the PSTools suite from SysInternals. Look for how to run as Local System with PSExec.exe There could be other ways as well, but this worked perfectly for me. 

My offer still stands with that said for troubleshooting the other issue if that is desired, just let me know. But again, it might go in that won't fix category based on being able to use Local System instead of the user account.

**Comment by krayon007** [comment] 2022-06-03 19:27
It looks like this scenario is covered, especially if you are able to use the new WebRDP connection. If you are still experiencing issues related to this, please re-open.

**Closed by krayon007** 2022-06-03 19:27 UTC
Labels: bug
